version: '3.7'
services:
  web:
    restart: always
    build: .
    command: python /code/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - 8000:8000
    depends_on:
      - db

  db:
    image: postgres:latest
    environment:
      - POSTGRES_USER=postgresid
      - POSTGRES_PASSWORD=testuser123
      - POSTGRES_DB=postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    expose:
      - 5432
      
volumes:
  postgres_data:



