# Generated by Django 3.0.8 on 2020-07-21 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ToyMode',
            new_name='ToyModel',
        ),
    ]
