# Generated by Django 3.0.8 on 2020-07-21 18:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20200721_1759'),
    ]

    operations = [
        migrations.AddField(
            model_name='toymodel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='toymodel',
            name='name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='toymodel',
            name='description',
            field=models.TextField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='toymodel',
            name='category',
            field=models.CharField(default='', max_length=50),
        ),

        migrations.AddField(
            model_name='toymodel',
            name='price',
            field=models.PositiveIntegerField(default=100),
        ),
        migrations.AddField(
            model_name='toymodel',
            name='was_included_in_home',
            field=models.BooleanField(default=False),
        ),
    ]
